enh: add support for setting inventory items for multiple slots at once
pvme/preset-maker pull request #3
Opened 2023-02-18 09:01 UTC by cdtinney

To do so, Shift+Click each slot. Then, click one of the slots to assign the same item to multiple slots.

If multiple slots are selected and some other slot is clicked, the selection is cleared.

Example UI:

![image](https://user-images.githubusercontent.com/3266047/219851744-d5bb1117-53fd-4718-a611-c26ecba288da.png)
![image](https://user-images.githubusercontent.com/3266047/219851749-cefa1a79-ad9b-41b3-974f-b7accebbb254.png)

2023-02-20 21:11 UTC, nullopt requested changes

2023-02-20 21:12 UTC, cdtinney commented on src/components/PresetEditor/PresetEditor.tsx
> +        // FIXME: This doesn't propagate correctly to the opened dialog - it still thinks theres
Nope, added that comment and then fixed it

2023-02-24 20:29 UTC, txj-xyz commented
@nullopt

2023-03-08 18:10 UTC, nullopt approved these changes

2023-03-08 18:10 UTC, merged